version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: afentoe
    ports:
      - 3000:80
    volumes:
      - .:/app/
      - /app/node_modules/
